### ISSUE TITLE
Authorization Token Failed

### ISSUE THREAD

**Issue by pointia** [be-cloud-js/open-erp-modules#4]
We use odoo with this extension and everytime i want to open page where the possibility exist to upload a document i get following error:

Cannot get authorization token for Google Drive:
access_denied - immediate_failed

I tried to google that error but i didn't find anything. A other user is using the same instance without any problem (so the oauth token is created and so on).

We both have access to the same google account if this is needed.

If i set 'immediate': true, to false i don't get any information and the plugin is still not working.

**Comment by letzdoo-js** [comment]
Hello,

Which version are you using 8.0 or 9.0 ?

Can you look into the browser console to see if anything appears there ?

Regards,

Jerome

**Comment by pointia** [comment]
Hi,
I'm using the latest version of 8.0 and the last commit of your extension and there are no entries in the browser console.

**Comment by letzdoo-js** [comment]
I just backported an improvement from 9.0 to 8.0.

Can you give it another try ?

Many thanks !!

**Comment by pointia** [comment]
Hi Jerome,

i tried it and now the popup appears, thanks for the fast solution.
I think the problem was that i was logged into 2 google accounts at the same time and the extension tried to access the first one even if the second one had the access rights for the gdrive account.

I hope this information is valuable for U.

Thanks a lot!
